name: Deploy Infrastructure

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - "terraform/**"
      - ".github/workflows/terraform_deploy.yml"

permissions:
  id-token: write
  contents: read

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2
        with:
          terraform_version: 1.11.2

      - name: Terraform Init
        run: |
          cd terraform
          terraform init

      - name: Terraform Validate
        run: |
          cd terraform
          terraform validate

      - name: Terraform Plan
        run: |
          cd terraform
          terraform plan -var="vpc_id=${{ secrets.VPC_ID }}" -var="subnet_id=${{ secrets.SUBNET_ID }}" -out=tfplan

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve tfplan
